### ISSUE TITLE
Can't convert specific stream

### ISSUE THREAD

**Issue by beowulf79** [RReverser/mpegts#8]
Hi, 

congratulations, you made an hell of a good job ;-)

I saved locally on my web server a short sample stream from www.atnnetwork.com but I get this error while playing with mpegts on chrome (i added some debug into index.js):

XHR finished loading: GET "http://localhost/RReverser-mpegts/atn-ts/playlist.m3u8". index.js:152
responseText #EXTM3U
# EXT-X-TARGETDURATION:10
# EXT-X-MEDIA-SEQUENCE:5067417
# EXTINF:10,

00017562.ts
# EXTINF:10,

00017563.ts
# EXTINF:10,

00017564.ts
# EXTINF:10,

00017565.ts
lastOriginal http://localhost/RReverser-mpegts/atn-ts/00017565.ts
asked for 4 more videos index.js:149
4
Uncaught TypeError: Unexpected value (52 !== 71). jdataview.github.io/dist/jbinary.js:1
XHR finished loading: POST "http://mc.yandex.ru/watch/23392234?page-url=http%3A%2F%2Flocalhost%2FRRever…%2C%2C%2C%2C%2C%2C%2C%2C%2C2454%2C2454%2C1%2C%3Arqnl%3A1%3Ast%3A1404978414". watch.js:49

Wrong format ?

Thanks for your help.

**Comment by RReverser** [comment]
Bug description is pretty useless without sample files.
Could you attach links to those files please?

**Comment by beowulf79** [comment]
Thanks for getting back to me;
I've just uploaded them here http://www.verdelli.net/RReverser-mpegts/mpegts-atn.html

**Comment by RReverser** [comment]
You can't just "upload" stream by putting only `m3u8` file. If you look at Network tab, you'll see that all the requests to *.ts files return "404 Not Found".

**Comment by beowulf79** [comment]
It looks to me that files are there, look to the attached image:

![screen shot 2014-07-11 at 21 37 16](https://cloud.githubusercontent.com/assets/8068498/3557756/5815377a-0933-11e4-9a59-558afb54c302.png)

**Comment by RReverser** [comment]
Check out contents of any of those files. Your web server returns code 200 by mistake, but contents of any of .ts files are "404 Not Found".

**Comment by beowulf79** [comment]
You were right, somehow uploading the file to the ftp server didn't not succeeded. 
Now they should be fine, similar error though.

**Comment by beowulf79** [comment]
Hi @RReverser ,
have you had the chance to look into the issue ?

thank you.

**Comment by RReverser** [comment]
Not much. As you said, it looks like format/encoding incompatibility problem, but can't investigate deeper for now due to lack of time.

**Comment by trong** [comment]
The same problem:

```
TypeError: Unexpected value (54 !== 71).
    at Object.defaultTypeSet.const.Template.read (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:312:23)
    at jBinary.<anonymous> (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:231:25)
    at jBinary.<anonymous> (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:225:34)
    at jBinary.proto._action (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:227:79)
    at jBinary.proto.read (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:230:21)
    at jBinary.<anonymous> (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:396:105)
    at jBinary.<anonymous> (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:398:25)
    at jBinary.proto.inContext (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:131:31)
    at Object.defaultTypeSet.object.Type.read (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:394:32)
    at jBinary.<anonymous> (/Users/trong/node_modules/mpegts_to_mp4/node_modules/jbinary/dist/node/jbinary.js:231:25)
```

https://dl.dropboxusercontent.com/u/17497896/ts-for-test/1060-50Num4789207.ts
https://dl.dropboxusercontent.com/u/17497896/ts-for-test/1060-50Num4789208.ts

**Comment by gliese1337** [comment]
I've just also run into this. I get a steady stream of these errors when trying to play a stream from Brightcove's CDN.

(I would provide the URL, but I'm not sure if that would be violating copyright licenses or not, so, sorry.)
